baseURL: "https://talgat.tech/"
languageCode: en-us
title: 
theme: hugo-PaperMod

params:
  homeInfoParams:
    Title: 'Talgat Sovetbekov'
    Content: 'Software engineering, KTL Alumni, Mountain & Gym lover'
  socialIcons:
    - name: github 
      url: "https://github.com/sovetbekov"

    - name: linkedin
      url: "https://www.linkedin.com/in/talgat-sovetbekov-1a015b204/"

    - name: telegram
      url: "https://t.me/talgatsb"
    
    - name: email
      url: "mailto:sovvetbekov@gmail.com"
    
    - name: spotify
      url: "https://open.spotify.com/playlist/2630fWOLLz9HLSa2lbkcVG?si=223f06a406eb4cf4"

  ShowReadingTime: true